#!/bin/bash

# evaluates on generated test cases.

for net in fc1 fc2 fc3 fc4 fc5 conv1 conv2 conv3 conv4 conv5
do
	echo Evaluating network ${net}...
	echo \tOn \"maybe robust\" test cases (should \"maybe\" output \'verified\')
	for spec in `ls ../test_cases/${net}/maybe_robust`
	do
		echo \t\t${spec}: 
		python verifier.py --net ${net} --spec ../test_cases/${net}/${spec}
	done
	echo \tOn non-robust test cases (should output \'not verified\')
	for spec in `ls ../test_cases/${net}/not_robust`
	do
		echo \t\t${spec}: 
		python verifier.py --net ${net} --spec ../test_cases/${net}/${spec}
	done
done
