#!/bin/bash

# evaluates on generated test cases.

for net in fc1 fc2 fc3 fc4 fc5 conv1 conv2 conv3 conv4 conv5
do
	echo "Evaluating network ${net}..."
	echo -e "\tOn \"maybe robust\" test cases (should \"maybe\" output 'verified')"
	for spec in `ls ../test_cases_generated/${net}/maybe_robust`
	do
		echo -ne "\t\t${spec}: \t"
		timeout 2m python verifier.py --net ${net} --spec ../test_cases_generated/${net}/maybe_robust/${spec} || echo "not verified"
	done
	echo -e "\tOn non-robust test cases (should output 'not verified')"
	for spec in `ls ../test_cases_generated/${net}/not_robust`
	do
		echo -ne "\t\t${spec}: \t"
		timeout 2m python verifier.py --net ${net} --spec ../test_cases_generated/${net}/not_robust/${spec} || echo "not verified"
	done
done
