#!/bin/bash

# a little script for quick and dirty testing.

usage="Usage: my_test <v || nv> <net> [timeout]\n
	\tv for verbose, nv for not-verbose\n
	\tnet must be one of: fc1 fc2 fc3 fc4 fc5 conv1 conv2 conv3 conv4 conv5\n
	\ttimeout is to be specified in seconds (default: 3 seconds)"

if [[ $# -ne 2 && $# -ne 3 ]]; then
	echo -e ${usage}
	exit 0
fi

if [[ $1 == "v" ]]; then
	verbosity="--myverbose"
elif [[ $1 == "nv" ]]; then
	verbosity=""
else
	echo -e ${usage}
	exit 0
fi

net=$2

if [[ $# -eq 3 ]]; then
	t=$3
else
	t=3 # timeout: 3 seconds by default
fi

if [[ ${net} == "fc1" ]]; then
	# spec="img0_0.06000.txt"
	spec="img1_0.07500.txt"
elif [[ ${net} == "fc2" ]]; then
	# spec="img0_0.05500.txt"
	spec="img1_0.04100.txt"
elif [[ ${net} == "fc3" ]]; then
 	spec="img0_0.00520.txt"
 	spec="img1_0.00900.txt"
elif [[ ${net} == "fc4" ]]; then
 	spec="img0_0.12300.txt"
 	spec="img1_0.12000.txt"
elif [[ ${net} == "fc5" ]]; then
	spec="img0_0.08000.txt"
	spec="img1_0.07200.txt"
elif [[ ${net} == "conv1" ]]; then
 	spec="img0_0.00200.txt"
	# spec="img1_0.02520.txt"
elif [[ ${net} == "conv2" ]]; then
 	spec="img0_0.10000.txt"
 	spec="img1_0.08200.txt"
elif [[ ${net} == "conv3" ]]; then
 	spec="img0_0.07700.txt"
 	spec="img1_0.09100.txt"
elif [[ ${net} == "conv4" ]]; then
 	spec="img0_0.01240.txt"
 	spec="img1_0.12300.txt"
elif [[ ${net} == "conv5" ]]; then
 	spec="img0_0.18500.txt"
 	spec="img1_0.21000.txt"
else
	echo -e ${usage}
	exit 0
fi



echo "Evaluating network ${net}..."
# echo -ne "\ttest_cases/${net}/${spec}: \t"
# timeout ${t}s python verifier.py --net ${net} --spec ../test_cases/${net}/${spec} ${verbosity} || echo "timed out (or error)"

echo -e "\tOn verifiable test cases (should output 'verified')"
for spec in `ls ../preliminary_submission_test_cases/${net}/maybe_robust`
do
	echo -ne "\t\t${spec}: \t"
	timeout ${t}s python timed_verifier.py --net ${net} --spec ../preliminary_submission_test_cases/${net}/maybe_robust/${spec} || echo "not verified"
done

# echo -e "\tOn non-robust test cases (should output 'not verified')"
# for spec in `ls ../preliminary_submission_test_cases/${net}/not_robust`
# do
# 	echo -ne "\t\t${spec}: \t"
# 	timeout ${t}s python timed_verifier.py --net ${net} --spec ../preliminary_submission_test_cases/${net}/not_robust/${spec} || echo "not verified"
# done
