#!/bin/bash

# a little script for quick and dirty testing.

if [[ $# -ne 1 ]]; then
	echo "Usage: my_test <v || nv> (verbose or not-verbose)"
	exit 0
else
	if [[ $1 == "v" ]]; then
        verbosity="--myverbose"
    else if [[ $1 == "nv" ]]; then
        verbosity=""
    else
        echo "Usage: my_test <v || nv> (verbose or not-verbose)"
        exit 0
    fi fi
fi

# net=fc1
# spec="img1_0.07500.txt"
# net=fc2
# spec="img1_0.04100.txt"
net=conv1
spec="img0_0.00200.txt"
t=3

echo "Evaluating network ${net}..."
echo -ne "\ttest_cases/${net}/${spec}: \t"
timeout ${t}s python verifier.py --net ${net} --spec ../test_cases/${net}/${spec} ${verbosity} || echo "timed out (or error)"
